### ISSUE TITLE
Webkit filter

### ISSUE THREAD

**Issue by jejacks0n** [maccman/gfx#5]
It may fall too far from the tree for this project, but I'll put it out as a proposal none-the-less.

http://html5-demos.appspot.com/static/css/filters/index.html

I'm working on a project where I'll be taking advantage of these upcoming features (see Canary and nightly Webkit builds), and am curious if you would be accepting of a pull request with some of these additions.

**Comment by maccman** [comment]
Sure!

**Comment by jejacks0n** [comment]
Perfect.  Two questions about the approach you'd most like to see me take.

1 -webkit-filter works the same as -webkit-transform (chaining properties into one declaration):

```
-webkit-transform: perspective(500px) rotateY(20deg)
```

I can see in the readme that these are separate attributes that can be animated.. I'm guessing you have logic that puts these together into the one value.  I expect the same would be true for -webkit-filter.. so in terms of usage it would look something like:

```
.gfx({
  perspective: "500px",
  rotateY: "20deg",
  blur: "6" // translated to "6px"?
  saturate: "3.4"
})
```

The attributes supported by -webkit-filter would be filtered out and put into a different declaration.

2 Based on how it appears gfx works, you're not using any intervals or timers for the animations.. do you ever fall back to this method, or is it strictly using css duration?  The reason I ask is that I haven't yet checked/confirmed that -webkit-filter adheres to these.

I'll do more investigation into this shortly, but wanted to get your input before I did anything.
